spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_application
    username: sahil
    password: sahil@sahil
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9090
  context-path: studentApplication
